class Locators:
    TITLE_NEW = '//div[@data-role="title" and text()="New"]'
    TITLE_YES = ('//div[@data-role="title" and text()="New"]/following-sibling::'
                 ' div[@data-role="content"]//a[contains(text(), "Yes")]')

    PRODUCT_IMAGE_CONTAINER = '.product-image-container'
    TOTAL_NUMBER = 'xpath=//p[@id="toolbar-amount"]/span[@class="toolbar-number"]'
    PRODUCT_IMAGE_WRAPPER = '.product-image-wrapper'
    COMPARE_BUTTON = '.tocompare'
    PRODUCT_ITEM_LINK = '.product-item-link'
    COMPARE_ITEM_LINK = '//ol[@id="compare-items"]//li//strong/a'
    ADD_TO_WISHLIST = '.action.towishlist'
    TEXT_WOMEN_DEALS = 'text="Shop Women’s Deals"'
    TEXT_JACKETS = 'text="Jackets"'
    TITLE_BASE = '.base'
    SALE_MENS = '.sale-mens'
    SALE = '#ui-id-8 span'
    PRODUCT_ITEM_NAME = '.product-item-name'
    FIRST_NAME = '#firstname'
    LAST_NAME = '#lastname'
    EMAIL = '#email_address'
    PASSWORD = '#password'
    PASSWORD_CONFIRM = '#password-confirmation'
    MESSAGE_SUCCESS = 'div.message-success'
    MESSAGE_ERROR = 'div.message-error'
    EMAIL_ERROR = '#email_address-error'
